### ISSUE TITLE
github error

### ISSUE THREAD

**Issue by slebedeva** [emilyskidsister/hacklily#55]
I cannot save file to github, getting  "Error: Could not save file."
I tried renaming main to master.
If I upload a .ly file to sheet-music/master, I can open it in hacklily.org. But I again cannot save it.
Firefox / Ubuntu 22.04.
Thank you!

**Comment by wgruenberger** [comment]
I got the same issue
errors from browser console:
`ReferenceError: process is not defined
    at index.js:2:5305104
    at u (index.js:2:3594319)
    at Generator._invoke (index.js:2:3594072)
    at Generator.next (index.js:2:3594682)
    at r (index.js:2:3623087)
    at a (index.js:2:3623290)
index.js:2 Error: Could not save file.
    at index.js:2:5326433
    at u (index.js:2:3594319)
    at Generator._invoke (index.js:2:3594072)
    at Generator.throw (index.js:2:3594682)
    at r (index.js:2:3623087)
    at l (index.js:2:3623326)`
let me me know if i can help, thank you

**Comment by jdalbey** [comment]
Also having this error appear (in a javascript alert box).  Also Firefox on Linux Mint.

**Comment by pmatos** [comment]
Same here. I tried it today for the first time and hacklily cannot save files.

**Comment by davekobrenski** [comment]
@jocelyn-stericker - this appears to be because the process.env vars aren't available on the client side. The fix is easy: in your `webpack.config.js`, add this right above the `webpack.EnvironmentPlugin` declaration:

```js
new webpack.DefinePlugin({
   'process.env': JSON.stringify(process.env)
}),
```

I'm able to save to my GitHub repo now (using my own org's credentials, for testing).

Just to be safe, I also added `"node": true` to the "env" section of the `.eslintrc.js` file (although I'm not sure it's needed). 

```json
"env": {
  "browser": true,
  "es6": true,
  "node": true
},
```

**Comment by korgmanGR** [comment]
@davekobrenski So I have to self-host?

**Comment by jocelyn-stericker** [comment]
In case anyone is still watching, this should now be resolved.
